### ISSUE TITLE
[Feature request]Support archiving conf and output file after running each test block 

### ISSUE THREAD

**Issue by spacewander** [openresty/test-nginx#42]
Will there be a helper function, like `archive_path './run'`, to archive generated files in a specific path?
With generated files and output archived after running tests, the process of debug will speed up and bug hunting will become much easier.

**Comment by agentzh** [comment]
What do you mean by "generated files"? Are you aware of the `--- ONLY` special test block section and the `TEST_NGINX_CHECK_ACCUM_ERR_LOG` environment?

**Comment by spacewander** [comment]
"generated files" means nginx.conf or/and other files generated by test-nginx.

If there are N tests failed, I have to add `--- ONLY` N times, and run the test at least N times, to check result one by one. And after each run, I need to remove the `--- ONLY` data section of current test.

Moreover, archiving generated files and output benefits to further analysis, especially for tests running in CI environment.

**Comment by agentzh** [comment]
@spacewander But in reality, after fixing a bug, there can be a bunch of failed tests that get passed again. And you still need to run the failed tests again to verify the effect of your fixes and the most effective way is to run the test case you are fixing individually. And running an individual test block to verify a fix may repeat several times since your initial attempts might be wrong or incomplete.

**Comment by agentzh** [comment]
@spacewander Your proposal is surely technically possible though I doubt its value in the real world. Well, I can accept a pull request from you to implement this through a special system environment. Essentially it's about copying `t/servroot/` to a separate directory for each test block in a special output directory. And you need to be careful about re-naming `t/servroot/` to something that can easily get mapped to the original test block ID. Well, it can be a bit messy. Just be careful.
