### ISSUE TITLE
support for stream blocks

### ISSUE THREAD

**Issue by lusis** [openresty/test-nginx#47]
The support added for `stream` configs should be added to the library. Unfortunately I don't know the code base well enough to add it. I'm still learning it but if someone can add it much quicker than I can add it and make a PR that would be awesome!

**Comment by agentzh** [comment]
@lusis What exactly are you looking for? Since you didn't give me examples, I'm not sure what exactly your requirements are.

We already have various different support for the nginx stream subsystem for different use cases.

See

https://openresty.gitbooks.io/programming-openresty/content/testing/testing-erroneous-cases.html

And

https://github.com/openresty/stream-lua-nginx-module/blob/master/t/002-content.t

**Comment by lusis** [comment]
@agentzh thank you! I searched all over for defining stream servers in test cases and had no luck. I even dug into the openresty tests and didn't find it. 

If it's okay iight opens few PRs on the documentation to make that information a bit more discoverable.

Please feel free to close this issue and thanks again.

**Comment by agentzh** [comment]
@lusis Sure. You're always welcome to submit PRs for better docs :) Thanks!
